apiVersion: skaffold/v3
kind: Config

metadata:
  name: habit-tracking-app

deploy:
  kubectl:
    defaultNamespace: ld-rr
  statusCheck: true

manifests:
  rawYaml:
  - ./k8s/*.yaml
  - ./k8s/**/**.yaml
  - ./k8s/**/**/**.yaml
  - ./k8s/**/**/**/**.yaml

build:
  artifacts:
  - image: ahmadsaeedgoda/ld_rr:auth-service
    context: src/services/auth
    docker:
      dockerfile: Dockerfile
      # buildArgs:
      #   APP_PORT: "3000"
    sync:
      manual:
      - src: "**/*"
        dest: .

  - image: ahmadsaeedgoda/ld_rr:auth-postgres
    context: ./src/services/auth/src/database
    docker:
      dockerfile: ./Dockerfile.postgres
      buildArgs:
        POSTGRES_HOST: auth-postgres
        POSTGRES_PORT: "5432"
        POSTGRES_DB: nodejs_habit_tracker_users
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password

      # manifests:
      #   rawYaml:
      #   - env-configmap.yaml
      #   - auth-postgres-data-persistentvolumeclaim.yaml
      #   - auth-postgres-deployment.yaml
      #   - auth-postgres-service.yaml
      #   - auth-service-claim0-persistentvolumeclaim.yaml
      #   - auth-service-deployment.yaml
      #   - auth-service-service.yaml
      #   - habit-service-claim0-persistentvolumeclaim.yaml
      #   - habit-service-deployment.yaml
      #   - habit-service-service.yaml
      #   - habits-postgres-data-persistentvolumeclaim.yaml
      #   - habits-postgres-deployment.yaml
      #   - habits-postgres-service.yaml
  # - k8s/ingress.yaml
  # - k8s/ld-namespace.yaml
  # - k8s/deployments/auth-deployment.yaml
  # - k8s/deployments/auth-postgres-deployment.yaml
  # - k8s/deployments/habits-deployment.yaml
  # - k8s/deployments/habits-postgres-deployment.yaml
  # - k8s/pvcs/auth-postgres.yaml
  # - k8s/pvcs/habits-postgres.yaml
  # - k8s/services/auth-postgres.yaml
  # - k8s/services/auth-service.yaml
  # - k8s/services/habit-service.yaml
  # - k8s/services/habits-postgres.yaml
