apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habit-tracker-auth-ingress
spec:
  rules:
  - host: habit-tracker-auth.local
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 3000
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habit-tracker-habits-ingress
spec:
  rules:
  - host: habit-tracker-habits.local
    http:
      paths:
      - path: /api/v1/habits
        pathType: Prefix
        backend:
          service:
            name: habits-service
            port:
              number: 3001
  ingressClassName: nginx
