apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: habits-postgres-pvc
  namespace: ld-rr
  labels:
    app: habits-postgres-pvc
    tier: backend
    environment: development
    role: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "256Mi"
