apiVersion: apps/v1
kind: Deployment
metadata:
  name: habits-deployment
  namespace: ld-rr
  labels:
    app: habits-service
    tier: backend
    environment: development
spec:
  selector:
    matchLabels:
      app: habits-service
      tier: backend
      environment: development
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: habits-service
        tier: backend
        environment: development
    spec:
      containers:
      - image: ahmadsaeedgoda/ld_rr:habit-service
        imagePullPolicy: IfNotPresent
        name: habits-deployment
        ports:
        - containerPort: 3001
        env:
        - name: APP_PORT
          value: "3001"
        - name: POSTGRES_HOST
          value: habits-postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: nodejs_habit_tracker_habits
        - name: AUTH_SERVICE_BASE_URL
          value: http://auth-service
        - name: AUTH_SERVICE_PORT
          value: "3000"
        - name: AUTH_SERVICE_PUBLIC_KEY_PATH
          value: public-key
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
