namespace: dev

dockerHubRegistryRepoName: ahmadsaeedgoda/ld_rr

auth:
  serviceName: auth-service
  appLabel: auth
  podName: auth-pod
  appPort: 3000
  DBServiceName: auth-postgres-service
  DBPortNum: 5432
  DBUser: admin
  DBPass: password
  DBName: nodejs_habit_tracker_users
  DBLabel: auth-postgres-app

habits:
  appPort: 3001
  appLabel: habits
  DBServiceName: habits-postgres-service
  DBPortNum: 5432
  DBUser: admin
  DBPass: password
  DBName: nodejs_habit_tracker_habits
  DBLabel: habits-postgres-app

ingress:
  enabled: true
  className: nginx
  annotations:
    # Reference: https://kubernetes.github.io/ingress-nginx/examples/rewrite/
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
  - host: habit-tracker-helm.local.dev
    paths:
    - path: /(/|$)(.*)
      pathType: ImplementationSpecific
