apiVersion: v1
kind: Service
metadata:
  name: habits-postgres
  namespace: ld-rr
  labels:
    app: habits-postgres
    tier: backend
    environment: development
    role: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5433
  selector:
    app: habits-postgres
