name: CI

on:
  push:
    branches:
      - feature/render-CD-demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd ./src/services/auth && docker build -t ahmadsaeedgoda/ld_rr:render-auth-service -f Dockerfile.staging.uat .
        docker push ahmadsaeedgoda/ld_rr:render-auth-service

    - name: Generate Public/Private Keys for JWT auth functionality
      run: |
        openssl genrsa -out ./certs/private.pem
        openssl rsa -in ./certs/private.pem -pubout -out ./certs/public.pem

    - name: Trigger Render Deploy Hook
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
# Test deployment trigger
